version: '3.7'

services:
  client:
    container_name: app-client
    build:
      context: ./
      dockerfile: Dockerfile
    # volumes:
    #   - './:/app'
    #   - '/app/node_modules'
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge