version: '3.7'

services:
  server:
    container_name: pricewatcher-server
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DOCKER_MODE=${DOCKER_MODE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 8000:8000
    # command: npm start
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./
    #       target: /
    #       ignore:
    #         - node_modules/
    #     - action: rebuild
    #       path: package.json
    networks:
      - pricewatcher-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - 'mysqlData:/var/lib/mysql'
    ports:
      - 33006:3306
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - pricewatcher-network

volumes:
  mysqlData:
    driver: local

networks:
  pricewatcher-network:
    driver: bridge