FROM python:3.8-slim

WORKDIR /app

COPY . /app
USER root
RUN apt-get update                             \
 && apt-get install -y --no-install-recommends \
    ca-certificates curl firefox-esr           \
 && rm -fr /var/lib/apt/lists/*                \
 && curl -L https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz | tar xz -C /usr/local/bin \
 && apt-get purge -y ca-certificates curl

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

# CMD ["python", "app.py"]
CMD ["python3", "-m", "flask", "--debug", "run", "--host=0.0.0.0"]

# FROM selenium/standalone-chrome

# WORKDIR /app

# USER root
# RUN apt-get update && apt-get install python3-distutils -y
# RUN wget https://bootstrap.pypa.io/get-pip.py
# RUN python3 get-pip.py

# COPY . ./
# # RUN python3 -m pip install selenium


# RUN pip install --no-cache-dir -r requirements.txt

# EXPOSE 8080

# # start app
# # CMD ["python3", "-m", "flask", "--debug", "run"]
# CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]