version: '3.7'

services:
  web-scraper:
    container_name: app-scraper
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/app'
    command: ["python3", "-m", "flask", "--debug", "run", "--host=0.0.0.0"]
    # command: ["python3", "-m", "flask", "--debug", "run"]
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge